wrapper {
	gradleVersion = '8.14.3'
}

buildscript {
	repositories {
		mavenCentral()
		maven { url "https://jitpack.io" }
		maven { url 'https://plugins.gradle.org/m2/' }
		mavenLocal()
	}
	dependencies {
		classpath 'org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:4.1.0'
		classpath "com.avast.gradle:gradle-docker-compose-plugin:0.15.0"
        classpath "io.spring.gradle:dependency-management-plugin:1.1.7"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:3.5.7"
	}
}

allprojects {
	version = project.version

	apply plugin: 'java'
	apply plugin: 'java-library'
	apply plugin: 'groovy'
	apply plugin: 'maven-publish'
	apply plugin: 'org.unbroken-dome.test-sets'
	apply plugin: 'io.spring.dependency-management'
	apply from: "${rootDir}/libraries.gradle"
	apply from: "${rootDir}/publish.gradle"

	sourceCompatibility = '17'
	targetCompatibility = '17'
	repositories {
		mavenCentral()
		mavenLocal()
	}

	dependencyManagement {
		imports {
			mavenBom(libraries.spring_boot)
		}
	}

	testSets {
		integrationTest {
			dirName = 'test-integration'
		}
	}

	dependencies {
        annotationProcessor libraries.lombok
        compileOnly libraries.lombok
        compileOnly libraries.groovy

        implementation libraries.slf4j

        testImplementation libraries.groovy
        testImplementation libraries.junit
        testImplementation libraries.spock
        testRuntimeOnly libraries.junit_platform_launcher
        integrationTestRuntimeOnly libraries.junit_platform_launcher
	}

	test {
		useJUnitPlatform()
		reports.junitXml.destination = file('build/test-results')

		testLogging {
			events "passed", "skipped", "failed", "standardError"
			showStackTraces = true
			exceptionFormat = 'full'
		}
	}

	integrationTest {
		useJUnitPlatform()
		reports.junitXml.destination = file('build/test-integration-results')

		testLogging {
			events "passed", "skipped", "failed", "standardError"
			showStackTraces = true
			exceptionFormat = 'full'
		}
	}
	check.dependsOn integrationTest

	ext.isRunningOnCI = {
		System.getenv("CI") == "true"
	}

	plugins.withId('docker-compose') {
		def candidates = ['/opt/homebrew/bin/docker-compose', '/usr/local/bin/docker-compose']
		def resolved = candidates.find { new File(it).exists() }
		dockerCompose {
			executable = resolved ?: 'docker-compose'
		}
	}
}

configurations {
	provided
	tests
	runtime {
		exclude module: 'lombok'
	}

	compile {
		exclude module: 'groovy-all'
	}
}
