version: 2

references:
  container_config: &container_config
    docker:
      - image: arti.tw.ee/circle_openjdk13:latest
        user: circleci
      - image: postgres:10.9
        environment:
          POSTGRES_DB: idempotence4j_db
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
      - image: mariadb:10.3.13
        command: ['--innodb_flush_log_at_trx_commit=2', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
        environment:
          MYSQL_DATABASE: idempotence4j_db
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: username
          MYSQL_PASSWORD: password
    resource_class: medium
    environment:
      TERM: vt100
      GRADLE_OPTS: '-Dorg.gradle.console=plain'
  working_directory: &working_directory
    working_directory: ~/idempotence4j
  set_git_config: &set_git_config
    command: |
      mkdir -p ~/.ssh
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git config --global user.name "TransferWise CircleCI" && git config --global user.email circle@circle.tw.ee

jobs:
  build:
    <<: *working_directory
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: idempotence4j-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Assemble jar
          command: ./gradlew assemble --console=plain --no-daemon
      - run:
          name: Run tests
          command: ./gradlew check --console=plain --no-daemon --stacktrace
      - save_cache:
          paths:
            - ~/.gradle/
          key: idempotence4j-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - store_test_results:
          path: ./idempotence4j-test/build/test-results/
      - store_test_results:
          path: ./idempotence4j-core/build/test-results/
      - store_test_results:
          path: ./idempotence4j-jdbc/build/test-results/
      - store_test_results:
          path: ./idempotence4j-postgres/build/test-results/
      - store_test_results:
          path: ./idempotence4j-spring-boot-starter/build/test-results/
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  publish-snapshot:
    <<: *working_directory
    <<: *container_config
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/idempotence4j
      - restore_cache:
          key: idempotence4j-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run: *set_git_config
      - run:
          name: Publish artifacts
          command: ./gradlew publish --console=plain --stacktrace --info
  publish-release:
    <<: *working_directory
    <<: *container_config
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/idempotence4j
      - restore_cache:
          key: idempotence4j-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run: *set_git_config
      - run:
          name: Publish artifacts
          command: ./gradlew publish pushTag --console=plain --info --stacktrace

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish-snapshot:
          context: artifactory-deploy
          requires:
            - build
          filters:
            branches:
              ignore: master
      - publish-release:
          context: artifactory-deploy
          requires:
            - build
          filters:
            branches:
              only:
                - master
